<?php

namespace Lava\Locations;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesTableSeeder extends Seeder {

    public function run() {
        //Seed currencies table
        DB::table('loc_currencies')->delete();

        $currencies = array(
            array('id' => 1, 'name' => 'ADP - Andorran Peseta', 'code' => 'ADP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 2, 'name' => 'AED - UAE Dirham', 'code' => 'AED', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 3, 'name' => 'AFN - Afghanistan Afghani', 'code' => 'AFN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 4, 'name' => 'ALL - Albanian Lek', 'code' => 'ALL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 5, 'name' => 'AMD - Armenian Dram', 'code' => 'AMD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 6, 'name' => 'ANG - Netherlands Antillean Guilder', 'code' => 'ANG', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 7, 'name' => 'AOA - Angolan Kwanza', 'code' => 'AOA', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 8, 'name' => 'ARS - Argentine Peso', 'code' => 'ARS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 9, 'name' => 'ATS - Austrian Schilling', 'code' => 'ATS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 10, 'name' => 'AUD - Australian Dollar', 'code' => 'AUD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 11, 'name' => 'AUD - Christmas Island Dollar', 'code' => 'AUD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 12, 'name' => 'AUD - Cocos (Keeling) Is. Dollar', 'code' => 'AUD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 13, 'name' => 'AUD - Kiribati Dollar', 'code' => 'AUD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 14, 'name' => 'AUD - Nauru Dollar', 'code' => 'AUD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 15, 'name' => 'AUD - Norfolk Island Dollar', 'code' => 'AUD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 16, 'name' => 'AUD - Tuvalu Dollar', 'code' => 'AUD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 17, 'name' => 'AWG - Aruban Guilder', 'code' => 'AWG', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 18, 'name' => 'AZN - Azerbaijani Manat', 'code' => 'AZN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 19, 'name' => 'BAM - Bosnia & Herzegovinan Marka', 'code' => 'BAM', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 20, 'name' => 'BBD - Barbadian Dollar', 'code' => 'BBD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 21, 'name' => 'BDT - Bangladesh Taka', 'code' => 'BDT', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 22, 'name' => 'BEF - Belgian Franc', 'code' => 'BEF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 23, 'name' => 'BGN - Bulgarian Lev', 'code' => 'BGN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 24, 'name' => 'BHD - Bahraini Dinar', 'code' => 'BHD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 25, 'name' => 'BIF - Burundi Franc', 'code' => 'BIF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 26, 'name' => 'BMD - Bermudian Dollar', 'code' => 'BMD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 27, 'name' => 'BND - Brunei Dollar', 'code' => 'BND', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 28, 'name' => 'BOB - Bolivian Boliviano', 'code' => 'BOB', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 29, 'name' => 'BRL - Brazilian Real', 'code' => 'BRL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 30, 'name' => 'BSD - Bahamas Dollar', 'code' => 'BSD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 31, 'name' => 'BTN - Bhutan Ngultrum', 'code' => 'BTN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 32, 'name' => 'BWP - Botswanan Pula', 'code' => 'BWP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 33, 'name' => 'BYR - Belarusian Ruble', 'code' => 'BYR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 34, 'name' => 'BZD - Belizean Dollar', 'code' => 'BZD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 35, 'name' => 'CAD - Canadian Dollar', 'code' => 'CAD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 36, 'name' => 'CHF - Liechtenstein Franc', 'code' => 'CHF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 37, 'name' => 'CHF - Swiss Franc', 'code' => 'CHF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 38, 'name' => 'CLP - Chilean Peso', 'code' => 'CLP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 39, 'name' => 'CNH - Offshore Chinese Renminbi', 'code' => 'CNH', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 40, 'name' => 'CNY - Chinese Renminbi', 'code' => 'CNY', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 41, 'name' => 'COP - Colombian Peso', 'code' => 'COP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 42, 'name' => 'CRC - Costa Rican Colon', 'code' => 'CRC', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 43, 'name' => 'CUP - Cuban Peso', 'code' => 'CUP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 44, 'name' => 'CVE - Cape Verde Escudo', 'code' => 'CVE', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 45, 'name' => 'CYP - Cypriot Pound', 'code' => 'CYP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 46, 'name' => 'CZK - Czech Koruna', 'code' => 'CZK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 47, 'name' => 'DEM - German Mark', 'code' => 'DEM', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 48, 'name' => 'DJF - Djiboutian Franc', 'code' => 'DJF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 49, 'name' => 'DKK - Danish Krone', 'code' => 'DKK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 50, 'name' => 'DKK - Faroe Islands Krone', 'code' => 'DKK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 51, 'name' => 'DKK - Greenland Krone', 'code' => 'DKK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 52, 'name' => 'DOP - Dominican Republic Peso', 'code' => 'DOP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 53, 'name' => 'DZD - Algerian Dinar', 'code' => 'DZD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 54, 'name' => 'ECS - Ecuadorean Sucre', 'code' => 'ECS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 55, 'name' => 'EEK - Estonian Kroon', 'code' => 'EEK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 56, 'name' => 'EGP - Egyptian Pound', 'code' => 'EGP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 57, 'name' => 'ERN - Eritrean Nakfa', 'code' => 'ERN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 58, 'name' => 'ESP - Spanish Peseta', 'code' => 'ESP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 59, 'name' => 'ETB - Ethiopian Birr', 'code' => 'ETB', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 60, 'name' => 'EUR - Canary Islands Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 61, 'name' => 'EUR - Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 62, 'name' => 'EUR - French Guiana Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 63, 'name' => 'EUR - Guadeloupe Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 64, 'name' => 'EUR - Martinique Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 65, 'name' => 'EUR - Mayotte Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 66, 'name' => 'EUR - Monaco Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 67, 'name' => 'EUR - Montenegro Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 68, 'name' => 'EUR - Saint Pierre & Miquelon Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 69, 'name' => 'EUR - San Marino Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 70, 'name' => 'EUR - Vatican Euro', 'code' => 'EUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 71, 'name' => 'FIM - Finnish Markka', 'code' => 'FIM', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 72, 'name' => 'FJD - Fijian Dollar', 'code' => 'FJD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 73, 'name' => 'FKP - Falkland Islands Pound', 'code' => 'FKP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 74, 'name' => 'FRF - French Franc', 'code' => 'FRF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 75, 'name' => 'GBP - British Indian Ocean Pound', 'code' => 'GBP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 76, 'name' => 'GBP - British Pound', 'code' => 'GBP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 77, 'name' => 'GBP - Canton & Enderbury Is. Pound', 'code' => 'GBP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 78, 'name' => 'GBP - Guernsey Pound', 'code' => 'GBP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 79, 'name' => 'GBP - Isle of Man Pound', 'code' => 'GBP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 80, 'name' => 'GEL - Georgian Lari', 'code' => 'GEL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 81, 'name' => 'GHS - Ghana Cedi', 'code' => 'GHS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 82, 'name' => 'GIP - Gibraltar Pound', 'code' => 'GIP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 83, 'name' => 'GMD - Gambian Dalasi', 'code' => 'GMD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 84, 'name' => 'GNF - Guinean Franc', 'code' => 'GNF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 85, 'name' => 'GRD - Greek Drachma', 'code' => 'GRD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 86, 'name' => 'GTQ - Guatemalan Quetzal', 'code' => 'GTQ', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 87, 'name' => 'GYD - Guyanese Dollar', 'code' => 'GYD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 88, 'name' => 'HKD - Hong Kong Dollar', 'code' => 'HKD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 89, 'name' => 'HNL - Honduras Lempira', 'code' => 'HNL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 90, 'name' => 'HRK - Croatian Kuna', 'code' => 'HRK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 91, 'name' => 'HTG - Haitian Gourde', 'code' => 'HTG', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 92, 'name' => 'HUF - Hungarian Forint', 'code' => 'HUF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 93, 'name' => 'IDR - Indonesian Rupiah', 'code' => 'IDR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 94, 'name' => 'IEP - Irish Punt', 'code' => 'IEP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 95, 'name' => 'ILS - Israeli Shekel', 'code' => 'ILS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 96, 'name' => 'INR - Indian Rupee', 'code' => 'INR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 97, 'name' => 'IQD - Iraqi Dinar', 'code' => 'IQD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 98, 'name' => 'IRR - Iranian Rial', 'code' => 'IRR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 99, 'name' => 'ISK - Iceland Krona', 'code' => 'ISK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 100, 'name' => 'ITL - Italian Lira', 'code' => 'ITL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 101, 'name' => 'JMD - Jamaican Dollar', 'code' => 'JMD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 102, 'name' => 'JOD - Jordanian Dinar', 'code' => 'JOD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 103, 'name' => 'JPY - Japanese Yen', 'code' => 'JPY', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 104, 'name' => 'KES - Kenyan Shilling', 'code' => 'KES', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 105, 'name' => 'KGS - Kyrgyzstan Som', 'code' => 'KGS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 106, 'name' => 'KHR - Cambodian Riel', 'code' => 'KHR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 107, 'name' => 'KMF - Comoran Franc', 'code' => 'KMF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 108, 'name' => 'KRW - South Korean Won', 'code' => 'KRW', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 109, 'name' => 'KWD - Kuwaiti Dinar', 'code' => 'KWD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 110, 'name' => 'KYD - Cayman Islands Dollar', 'code' => 'KYD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 111, 'name' => 'KZT - Kazakhstan Tenge', 'code' => 'KZT', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 112, 'name' => 'LAK - Laotian Kip', 'code' => 'LAK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 113, 'name' => 'LBP - Lebanese Pound', 'code' => 'LBP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 114, 'name' => 'LKR - Sri Lankan Rupee', 'code' => 'LKR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 115, 'name' => 'LRD - Liberian Dollar', 'code' => 'LRD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 116, 'name' => 'LSL - Lesotho Loti', 'code' => 'LSL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 117, 'name' => 'LTL - Lithuanian Litas', 'code' => 'LTL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 118, 'name' => 'LUF - Luxembourg Franc', 'code' => 'LUF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 119, 'name' => 'LVL - Latvian Lats', 'code' => 'LVL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 120, 'name' => 'LYD - Libyan Dinar', 'code' => 'LYD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 121, 'name' => 'MAD - Moroccan Dirham', 'code' => 'MAD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 122, 'name' => 'MDL - Moldovan Leu', 'code' => 'MDL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 123, 'name' => 'MGA - Madagascar Ariary', 'code' => 'MGA', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 124, 'name' => 'MKD - Macedonian Denar', 'code' => 'MKD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 125, 'name' => 'MMK - Myanmar Kyat', 'code' => 'MMK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 126, 'name' => 'MNT - Mongolian Tugrik', 'code' => 'MNT', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 127, 'name' => 'MOP - Macau Pataca', 'code' => 'MOP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 128, 'name' => 'MRO - Mauritanian Ouguiya', 'code' => 'MRO', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 129, 'name' => 'MTL - Maltese Lira', 'code' => 'MTL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 130, 'name' => 'MUR - Mauritian Rupee', 'code' => 'MUR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 131, 'name' => 'MVR - Maldives Rufiyaa', 'code' => 'MVR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 132, 'name' => 'MWK - Malawian Kwacha', 'code' => 'MWK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 133, 'name' => 'MXN - Mexican Peso', 'code' => 'MXN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 134, 'name' => 'MYR - Malaysian Ringgit', 'code' => 'MYR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 135, 'name' => 'MZN - Mozambique New Metical', 'code' => 'MZN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 136, 'name' => 'NAD - Namibian Dollar', 'code' => 'NAD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 137, 'name' => 'NGN - Nigerian Naira', 'code' => 'NGN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 138, 'name' => 'NIO - Nicaraguan Cordoba', 'code' => 'NIO', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 139, 'name' => 'NLG - Netherlands (Dutch) Guilder', 'code' => 'NLG', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 140, 'name' => 'NOK - Norwegian Krone', 'code' => 'NOK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 141, 'name' => 'NPR - Nepalese Rupee', 'code' => 'NPR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 142, 'name' => 'NZD - Cook Islands Dollar', 'code' => 'NZD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 143, 'name' => 'NZD - New Zealand Dollar', 'code' => 'NZD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 144, 'name' => 'NZD - Niue Dollar', 'code' => 'NZD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 145, 'name' => 'NZD - Pitcairn Islands Dollar', 'code' => 'NZD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 146, 'name' => 'NZD - Tokelau Dollar', 'code' => 'NZD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 147, 'name' => 'OMR - Omani Rial', 'code' => 'OMR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 148, 'name' => 'PAB - Panamanian Balboa', 'code' => 'PAB', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 149, 'name' => 'PEN - Peruvian New Sol', 'code' => 'PEN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 150, 'name' => 'PGK - Papua New Guinea Kina', 'code' => 'PGK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 151, 'name' => 'PHP - Philippine Peso', 'code' => 'PHP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 152, 'name' => 'PKR - Pakistani Rupee', 'code' => 'PKR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 153, 'name' => 'PLN - Polish Zloty', 'code' => 'PLN', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 154, 'name' => 'PTE - Portuguese Escudo', 'code' => 'PTE', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 155, 'name' => 'PYG - Paraguay Guarani', 'code' => 'PYG', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 156, 'name' => 'QAR - Qatari Rial', 'code' => 'QAR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 157, 'name' => 'RON - Romanian Leu', 'code' => 'RON', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 158, 'name' => 'RSD - Serbian Dinar', 'code' => 'RSD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 159, 'name' => 'RUB - Russian Ruble', 'code' => 'RUB', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 160, 'name' => 'RWF - Rwandan Franc', 'code' => 'RWF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 161, 'name' => 'SAR - Saudi Riyal', 'code' => 'SAR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 162, 'name' => 'SBD - Solomon Islands Dollar', 'code' => 'SBD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 163, 'name' => 'SCR - Seychelles Rupee', 'code' => 'SCR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 164, 'name' => 'SEK - Swedish Krona', 'code' => 'SEK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 165, 'name' => 'SGD - Singapore Dollar', 'code' => 'SGD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 166, 'name' => 'SIT - Slovenian Tolar', 'code' => 'SIT', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 167, 'name' => 'SKK - Slovakian Koruna', 'code' => 'SKK', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 168, 'name' => 'SLL - Sierra Leone Leone', 'code' => 'SLL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 169, 'name' => 'SOS - Somali Shilling', 'code' => 'SOS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 170, 'name' => 'SRD - Suriname Dollar', 'code' => 'SRD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 171, 'name' => 'STD - Sao Tome & Principe Dobra', 'code' => 'STD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 172, 'name' => 'SVC - El Salvador Colon', 'code' => 'SVC', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 173, 'name' => 'SYP - Syrian Pound', 'code' => 'SYP', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 174, 'name' => 'SZL - Swaziland Lilangeni', 'code' => 'SZL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 175, 'name' => 'THB - Thai Baht', 'code' => 'THB', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 176, 'name' => 'THO - Thai Baht Onshore', 'code' => 'THO', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 177, 'name' => 'TJS - Tajikistani Somoni', 'code' => 'TJS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 178, 'name' => 'TMT - Turkmenistan Manat', 'code' => 'TMT', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 179, 'name' => 'TND - Tunisian Dinar', 'code' => 'TND', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 180, 'name' => 'TRL - Turkish Old Lira', 'code' => 'TRL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 181, 'name' => 'TRY - Turkish New Lira', 'code' => 'TRY', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 182, 'name' => 'TTD - Trinidad & Tobago Dollar', 'code' => 'TTD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 183, 'name' => 'TWD - Taiwanese Dollar', 'code' => 'TWD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 184, 'name' => 'TZS - Tanzanian Shilling', 'code' => 'TZS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 185, 'name' => 'UAH - Ukrainian Hryvnia', 'code' => 'UAH', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 186, 'name' => 'UGX - Ugandan Shilling', 'code' => 'UGX', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 187, 'name' => 'USD - East Timor Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 188, 'name' => 'USD - Guam Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 189, 'name' => 'USD - Johnston Atoll Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 190, 'name' => 'USD - Micronesian Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 191, 'name' => 'USD - Midway Islands Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 192, 'name' => 'USD - Northern Mariana Is. Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 193, 'name' => 'USD - Palau Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 194, 'name' => 'USD - Puerto Rican Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 195, 'name' => 'USD - Turks & Caicos Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 196, 'name' => 'USD - United States Dollar', 'code' => 'USD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 197, 'name' => 'UYU - Uruguayan Peso', 'code' => 'UYU', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 198, 'name' => 'UZS - Uzbekistani Soum', 'code' => 'UZS', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 199, 'name' => 'VEE - Venezuela Bolivar Essentials', 'code' => 'VEE', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 200, 'name' => 'VEF - Venezuelan Bolivar', 'code' => 'VEF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 201, 'name' => 'VND - Vietnamese Dong', 'code' => 'VND', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 202, 'name' => 'VUV - Vanuatu Vatu', 'code' => 'VUV', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 203, 'name' => 'WST - West Samoan Tala', 'code' => 'WST', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 204, 'name' => 'XAF - Cameroon Franc', 'code' => 'XAF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 205, 'name' => 'XAF - Central African Republic Franc', 'code' => 'XAF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 206, 'name' => 'XAF - CFA Franc BEAC', 'code' => 'XAF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 207, 'name' => 'XAF - Chad Franc', 'code' => 'XAF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 208, 'name' => 'XAF - Congo Republic Franc', 'code' => 'XAF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 209, 'name' => 'XAF - Equatorial Guinea Franc', 'code' => 'XAF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 210, 'name' => 'XAF - Gabon Franc', 'code' => 'XAF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 211, 'name' => 'XAG - Silver', 'code' => 'XAG', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 212, 'name' => 'XAU - Gold', 'code' => 'XAU', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 213, 'name' => 'XCD - Anguillan Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 214, 'name' => 'XCD - Antiguan & Barbudan Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 215, 'name' => 'XCD - Dominica Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 216, 'name' => 'XCD - East Caribbean Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 217, 'name' => 'XCD - Grenadan Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 218, 'name' => 'XCD - Montserrat Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 219, 'name' => 'XCD - St. Kitts & Nevis Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 220, 'name' => 'XCD - St. Lucia Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 221, 'name' => 'XCD - St. Vincent Dollar', 'code' => 'XCD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 222, 'name' => 'XOF - Benin Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 223, 'name' => 'XOF - Burkina Faso Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 224, 'name' => 'XOF - CFA Franc BCEAO', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 225, 'name' => 'XOF - Guinea-Bissau Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 226, 'name' => 'XOF - Ivory Coast Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 227, 'name' => 'XOF - Mali Republic Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 228, 'name' => 'XOF - Niger Republic Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 229, 'name' => 'XOF - Senegalese Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 230, 'name' => 'XOF - Togo Republic Franc', 'code' => 'XOF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 231, 'name' => 'XPD - Palladium', 'code' => 'XPD', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 232, 'name' => 'XPF - French Polynesian Franc', 'code' => 'XPF', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 233, 'name' => 'XPT - Platinum', 'code' => 'XPT', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 234, 'name' => 'YER - Yemeni Rial', 'code' => 'YER', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 235, 'name' => 'ZAR - South African Rand', 'code' => 'ZAR', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 236, 'name' => 'ZMW - Zambian Kwacha', 'code' => 'ZMW', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 237, 'name' => 'ZWL - Zimbabwean Dollar', 'code' => 'ZWL', 'status' => 1, 'created_by' => 1, 'updated_by' => 1, 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
        );

        //Unseed currencies table
        DB::table('loc_currencies')->insert($currencies);
    }

}
